### ISSUE TITLE
sigma  from pixels to normalized units

### ISSUE THREAD

**Issue by eejackliu** [anibali/dsnt-pose2d#2]
https://github.com/anibali/dsnt-pose2d/blob/f453331a6b120f02948336555b996ac0d95bf4be/src/dsnt/model.py#L48
I thought the normalized units is to make data range from 0 to 1. According to the code in class HumanPoseModel, sigma = (2.0 * hm_sigma / hm_var.size(-1)) is the normalized units. I can't understand why should make sigma divided by the width of heatmap . Could you give me some tips?
Thanks

**Comment by anibali** [comment]
Yeah, I'm not using the term "normalized" in the strict statistical sense there---the range of values is [-1, 1]. There's nothing particularly special about choosing this representation for coordinates in the heatmap, I just decided to write the `dsnt.nn` module to represent coordinates this way because training tends to work better for losses calculated with small values near zero. Then, for consistency, I also made the sigma argument accept normalized values too.

**Comment by eejackliu** [comment]
So, if I make sigma a small value like 0.1 instead of that equation. I still could get the same answer.
Am I right?

**Comment by anibali** [comment]
Yes, the equation is only ever evaluated on one value the way it is currently used, so it could be replaced with an appropriate constant.

**Comment by eejackliu** [comment]
Thank you for your answer!
